# CloudWatch Exporter Configuration for LocalStack
region: us-east-1
cloudwatch_endpoint: http://localstack:4566

metrics:
  - name: s3_bucket_size_bytes
    help: S3 bucket size in bytes
    type: gauge
    aws_namespace: AWS/S3
    aws_metric_name: BucketSizeBytes
    aws_dimensions: 
      - BucketName
      - StorageType
    aws_dimension_select:
      BucketName:
        - app
      StorageType:
        - StandardStorage
    aws_statistics: 
      - Average

  - name: s3_number_of_objects
    help: Number of objects in S3 bucket
    type: gauge
    aws_namespace: AWS/S3
    aws_metric_name: NumberOfObjects
    aws_dimensions:
      - BucketName
      - StorageType
    aws_dimension_select:
      BucketName:
        - app
      StorageType:
        - AllStorageTypes
    aws_statistics:
      - Average

  - name: s3_all_requests
    help: S3 bucket requests
    type: counter
    aws_namespace: AWS/S3
    aws_metric_name: AllRequests
    aws_dimensions:
      - BucketName
    aws_dimension_select:
      BucketName:
        - app
    aws_statistics:
      - Sum

  - name: s3_bytes_downloaded
    help: S3 bytes downloaded
    type: counter
    aws_namespace: AWS/S3
    aws_metric_name: BytesDownloaded
    aws_dimensions:
      - BucketName
    aws_dimension_select:
      BucketName:
        - app
    aws_statistics:
      - Sum

  - name: s3_bytes_uploaded
    help: S3 bytes uploaded
    type: counter
    aws_namespace: AWS/S3
    aws_metric_name: BytesUploaded
    aws_dimensions:
      - BucketName
    aws_dimension_select:
      BucketName:
        - app
    aws_statistics:
      - Sum