apiVersion: 1

groups:
  - name: application_alerts
    orgId: 1
    folder: alerts
    interval: 1m
    rules:
      - uid: app_down_alert
        title: Application Down
        condition: B
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: up{job="application"}
              interval: ""
              refId: A
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A < 1
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: classic_conditions
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          description: "The application appears to be down. No response from health check endpoint."
          summary: "Application is not responding"
        labels:
          severity: critical
          service: application

      - uid: high_response_time_alert
        title: High Response Time
        condition: B
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))
              interval: ""
              refId: A
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A > 1
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: classic_conditions
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: "Application response time (P95) is above 1 second"
          summary: "High response time detected"
        labels:
          severity: warning
          service: application

      - uid: high_error_rate_alert
        title: High Error Rate
        condition: B
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: prometheus
            model:
              expr: (sum(rate(http_requests_total{status_code=~"[45].*"}[5m])) / sum(rate(http_requests_total[5m]))) * 100
              interval: ""
              refId: A
          - refId: B
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 5
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A > 5
              intervalMs: 1000
              maxDataPoints: 43200
              refId: B
              type: classic_conditions
        noDataState: NoData
        execErrState: Alerting
        for: 3m
        annotations:
          description: "Application error rate is above 5%"
          summary: "High error rate detected"
        labels:
          severity: warning
          service: application
