apiVersion: 1

policies:
  - orgId: 1
    receiver: slack-alerts
    group_by: ['alertname', 'cluster', 'service']
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 1h
    routes:
      - receiver: slack-critical
        matchers:
          - severity = critical
        group_wait: 10s
        group_interval: 5s
        repeat_interval: 30m
      - receiver: slack-warning  
        matchers:
          - severity = warning
        group_wait: 30s
        group_interval: 1m
        repeat_interval: 1h